version: '3.9'

services:
  keycloak-mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    container_name: keycloak
    command: >
      start-dev
      --import-realm
      --db=mysql
      --db-url-host=keycloak-mysql
      --db-url-database=keycloak
      --db-username=keycloak
      --db-password=keycloak
      --hostname-strict=false
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9080:8080"
    depends_on:
      - keycloak-mysql
    volumes:
      - ./realm-config:/opt/keycloak/data/import