package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassRoomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomAllPropertiesEquals(ClassRoom expected, ClassRoom actual) {
        assertClassRoomAutoGeneratedPropertiesEquals(expected, actual);
        assertClassRoomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomAllUpdatablePropertiesEquals(ClassRoom expected, ClassRoom actual) {
        assertClassRoomUpdatableFieldsEquals(expected, actual);
        assertClassRoomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomAutoGeneratedPropertiesEquals(ClassRoom expected, ClassRoom actual) {
        assertThat(actual)
            .as("Verify ClassRoom auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomUpdatableFieldsEquals(ClassRoom expected, ClassRoom actual) {
        assertThat(actual)
            .as("Verify ClassRoom relevant properties")
            .satisfies(a -> assertThat(a.getClassName()).as("check className").isEqualTo(expected.getClassName()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getTeacherId()).as("check teacherId").isEqualTo(expected.getTeacherId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRoomUpdatableRelationshipsEquals(ClassRoom expected, ClassRoom actual) {
        // empty method
    }
}
